// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  모든 노드 조회
	 * 
	 *  # 마일스톤 1 구현
	 *  현재는 빈 배열 반환. 이유: DB 쿼리 레이어는 다음 마일스톤에서 구현.
	 *  이번 마일스톤의 목표는 "IPC 파이프가 정상 작동하는지 확인"이므로,
	 *  타입 시스템과 command 레지스트리가 올바르면 충분.
	 * 
	 *  # Tauri 매크로 `#[tauri::command]`
	 *  `#[tauri::command]` 매크로를 함수에 붙이면 Tauri가 자동으로:
	 *  1. 함수를 async 래퍼로 감싸기
	 *  2. 에러를 JSON으로 직렬화하기
	 *  3. 프론트엔드에서 호출 가능하게 등록하기
	 *  위 세 가지를 자동 생성. 매크로가 없으면 수동으로 이 모든 걸 해야 함.
	 * 
	 *  # async 키워드가 필요한 이유
	 * 
	 *  Rust의 async/await 문법: 함수가 "동시성"을 지원하게 만든다.
	 *  Tauri는 IPC 핸들러를 내부 tokio 비동기 런타임에서 실행한다.
	 *  따라서 command 함수는 반드시 async 함수여야 하고,
	 *  나중에 DB 쿼리(tauri-plugin-sql의 execute())나 파일 I/O가 들어오면
	 *  `.await`로 완료를 기다릴 수 있다.
	 *  현재는 DB가 없어서 await 블록이 없어 보이지만,
	 *  마일스톤 2에서 실제 DB I/O가 들어오면:
	 *    let nodes = db.query_all_nodes().await?;  // await 필수
	 *  로 변환된다.
	 * 
	 *  # 반환 타입 Result<Vec<Node>, String>
	 *  - `Ok(Vec<Node>)` — 성공, 노드 배열 반환
	 *  - `Err(String)` — 실패, 에러 메시지 반환 (사용자가 이해할 수 있는 한국어여야 함)
	 *  Rust의 Result<T, E> 패턴: 예외 던지기 대신 반환값에 성공/실패 담기.
	 *  호출자(Tauri)는 자동으로 Result를 JSON 성공/실패 응답으로 변환.
	 */
	getNodes: () => typedError<Node[], string>(__TAURI_INVOKE("get_nodes")),
	/**
	 *  노드 ID 하나에 대한 메타데이터 조회
	 * 
	 *  # 반환값
	 *  - `Ok(Some(details))` — 해당 ID 노드를 찾음
	 *  - `Ok(None)` — 해당 ID가 없음 (frontend에서 "선택된 노드 정보 없음"으로 처리)
	 *  - `Err(String)` — 시스템 에러 (현재 단계에선 발생 안 함)
	 * 
	 *  # 왜 `Result<Option<T>, E>`인가
	 *  - `Option`: 비즈니스 로직상의 "없음" (정상 흐름)
	 *  - `Result`: 시스템 레벨 실패 (DB connection error 등)
	 *  두 의미를 분리해야 frontend가 "조회 실패 (재시도)" vs "정보 없음" 구분 가능.
	 * 
	 *  # tauri-specta `#[specta::specta]`
	 *  `#[tauri::command]`만으로는 frontend에 invoke 함수 시그니처가 자동 생성되지
	 *  않는다. `#[specta::specta]`를 함께 붙여야 tauri-specta Builder가 메타정보를
	 *  수집해 `bindings.ts`에 타입 세이프 wrapper를 만든다.
	 */
	getNodeDetails: (id: string) => typedError<{
	id: string,
	name: string,
	path: string,
	kind: NodeKind,
	sizeBytes: number,
	createdAt: number,
	modifiedAt: number,
} | null, string>(__TAURI_INVOKE("get_node_details", { id })),
};

/* Types */
/**
 *  3D 공간 노드 (파일, 링크, 메모 등의 개체)
 * 
 *  # 필드
 *  - `id`: 고유 식별자 (UUID 형식 권장, 다음 마일스톤)
 *  - `path`: 로컬 파일시스템 경로 또는 URL (안전성 검증됨)
 *  - `x`, `y`, `z`: 3D 공간 좌표 (무한 캔버스 위치)
 * 
 *  # serde 매크로 설명
 *  `#[derive(Serialize, Deserialize)]`는 구조체를 자동으로 JSON ↔ Rust 객체 변환
 *  프론트엔드 `src/state/store.ts`의 `Node` 타입과 필드 이름/타입이 반드시 일치해야 함
 *  # `#[serde(rename_all = "camelCase")]` 설명
 * 
 *  Rust 필드 이름은 snake_case 관례 (예: `created_at`, `updated_at`),
 *  그러나 TypeScript/JavaScript는 camelCase 관례 (예: `createdAt`, `updatedAt`).
 *  이 attribute를 붙이면 serde가 직렬화 시 자동으로 snake_case → camelCase 변환.
 *  예를 들어 Rust의 `pub created_at: i64` 필드는 JSON에서 `"createdAt": ...` 로 변환됨.
 * 
 *  왜 지금 당장 필요한가? 현재 필드엔 snake_case가 없지만, 다음 마일스톤에서
 *  `created_at`, `updated_at`, `is_dirty` 같은 필드가 추가될 예정.
 *  지금 이 attribute를 추가하면 앞으로 TS 타입이 undefined로 읽히는 버그를 원천 차단.
 * 
 *  규약: 모든 IPC struct (Node, Project, Metadata 등)는 이 attribute를 반드시 부여.
 */
export type Node = {
	id: string,
	path: string,
	x: number,
	y: number,
	z: number,
};

/**
 *  노드 메타데이터 (선택된 노드 상세 정보 패널용)
 * 
 *  # 필드 타입 결정 근거 (Gemini Pro 자문, 2026-04-23)
 *  - `size_bytes: u64` — 파일 크기. JS Number는 53비트 안전 정수까지 (~9PB),
 *    파일 크기로는 충분. BigInt 변환 불필요.
 *  - `created_at`, `modified_at: i64` — Unix epoch milliseconds. i64는 ~300,000년
 *    범위라 안전. ISO 8601 string 대신 number로 보내는 이유: 페이로드 작고,
 *    파싱 빠르고, 정렬도 number 비교로 가능.
 * 
 *  # camelCase 자동 변환
 *  `size_bytes` → `sizeBytes`, `created_at` → `createdAt`, `modified_at` → `modifiedAt`.
 *  위 `#[serde(rename_all = "camelCase")]`가 처리. tauri-specta가 생성하는
 *  TypeScript 타입에도 자동으로 반영됨.
 */
export type NodeDetails = {
	id: string,
	name: string,
	path: string,
	kind: NodeKind,
	sizeBytes: number,
	createdAt: number,
	modifiedAt: number,
};

/**
 *  노드 종류 (파일/디렉터리/링크/메모)
 * 
 *  프론트엔드에서 아이콘/색상 분기에 사용할 분류값.
 *  `#[serde(rename_all = "camelCase")]` enum variant까지 camelCase로 변환되지는
 *  않지만 (variant는 PascalCase 그대로 유지), 일관성과 안전성 차원에서 부여.
 *  JSON 표현 예: `"file"`, `"directory"`, `"link"`, `"memo"`.
 */
export type NodeKind = "file" | "directory" | "link" | "memo";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

