// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  모든 노드 조회
	 * 
	 *  # 마일스톤 1 구현
	 *  현재는 빈 배열 반환. 이유: DB 쿼리 레이어는 다음 마일스톤에서 구현.
	 *  이번 마일스톤의 목표는 "IPC 파이프가 정상 작동하는지 확인"이므로,
	 *  타입 시스템과 command 레지스트리가 올바르면 충분.
	 * 
	 *  # Tauri 매크로 `#[tauri::command]`
	 *  `#[tauri::command]` 매크로를 함수에 붙이면 Tauri가 자동으로:
	 *  1. 함수를 async 래퍼로 감싸기
	 *  2. 에러를 JSON으로 직렬화하기
	 *  3. 프론트엔드에서 호출 가능하게 등록하기
	 *  위 세 가지를 자동 생성. 매크로가 없으면 수동으로 이 모든 걸 해야 함.
	 * 
	 *  # async 키워드가 필요한 이유
	 * 
	 *  Rust의 async/await 문법: 함수가 "동시성"을 지원하게 만든다.
	 *  Tauri는 IPC 핸들러를 내부 tokio 비동기 런타임에서 실행한다.
	 *  따라서 command 함수는 반드시 async 함수여야 하고,
	 *  나중에 DB 쿼리(tauri-plugin-sql의 execute())나 파일 I/O가 들어오면
	 *  `.await`로 완료를 기다릴 수 있다.
	 *  현재는 DB가 없어서 await 블록이 없어 보이지만,
	 *  마일스톤 2에서 실제 DB I/O가 들어오면:
	 *    let nodes = db.query_all_nodes().await?;  // await 필수
	 *  로 변환된다.
	 * 
	 *  # 반환 타입 Result<Vec<Node>, String>
	 *  - `Ok(Vec<Node>)` — 성공, 노드 배열 반환
	 *  - `Err(String)` — 실패, 에러 메시지 반환 (사용자가 이해할 수 있는 한국어여야 함)
	 *  Rust의 Result<T, E> 패턴: 예외 던지기 대신 반환값에 성공/실패 담기.
	 *  호출자(Tauri)는 자동으로 Result를 JSON 성공/실패 응답으로 변환.
	 */
	getNodes: () => typedError<Node[], string>(__TAURI_INVOKE("get_nodes")),
	/**
	 *  노드 ID 하나에 대한 메타데이터 조회
	 * 
	 *  # 반환값
	 *  - `Ok(Some(details))` — 해당 ID 노드를 찾음
	 *  - `Ok(None)` — 해당 ID가 없음 (frontend에서 "선택된 노드 정보 없음"으로 처리)
	 *  - `Err(String)` — 시스템 에러 (현재 단계에선 발생 안 함)
	 * 
	 *  # 왜 `Result<Option<T>, E>`인가
	 *  - `Option`: 비즈니스 로직상의 "없음" (정상 흐름)
	 *  - `Result`: 시스템 레벨 실패 (DB connection error 등)
	 *  두 의미를 분리해야 frontend가 "조회 실패 (재시도)" vs "정보 없음" 구분 가능.
	 * 
	 *  # tauri-specta `#[specta::specta]`
	 *  `#[tauri::command]`만으로는 frontend에 invoke 함수 시그니처가 자동 생성되지
	 *  않는다. `#[specta::specta]`를 함께 붙여야 tauri-specta Builder가 메타정보를
	 *  수집해 `bindings.ts`에 타입 세이프 wrapper를 만든다.
	 */
	getNodeDetails: (id: string) => typedError<{
	id: string,
	name: string,
	path: string,
	kind: NodeKind,
	sizeBytes: number,
	createdAt: number,
	modifiedAt: number,
} | null, string>(__TAURI_INVOKE("get_node_details", { id })),
	/**
	 *  (Step 1 호환) 디렉토리 스캔 결과를 한 번에 반환.
	 * 
	 *  작은 디렉토리에서만 사용. 큰 트리는 `start_directory_scan` 권장.
	 */
	scanDirectoryCommand: (path: string, maxDepth: number) => typedError<ScannedNode[], string>(__TAURI_INVOKE("scan_directory_command", { path, maxDepth })),
	/**
	 *  (Step 2) 청크 스트리밍 디렉토리 스캔.
	 * 
	 *  # 흐름
	 *  1. Frontend 가 `invoke('start_directory_scan', {path, maxDepth})` 호출.
	 *  2. 본 함수는 입력 검증 후 즉시 `Ok(())` 반환.
	 *  3. `tokio::spawn` 으로 백그라운드 task 생성, 그 안에서 `scan_directory_chunked` 호출.
	 *  4. 청크가 완성될 때마다 `chunk.emit(&app)` → frontend `events.nodeChunkEvent.listen()`.
	 *  5. 마지막 청크는 `is_last = true` (성공/실패 모두 종료 시그널 보장).
	 * 
	 *  # 왜 즉시 Ok 반환인가
	 *  큰 디렉토리(수만 노드)는 수 초 걸릴 수 있다. invoke 가 그동안 대기하면
	 *  frontend 에서 await 중인 promise 가 응답성을 잃는다. 청크 이벤트로만 진행상황을
	 *  알리고, 호출 자체는 fire-and-forget.
	 * 
	 *  # 에러 정책
	 *  - 입력 검증 (현재 없음) 실패 → invoke 단계에서 Err(String) 반환.
	 *  - 백그라운드 task 의 scanner 에러 → eprintln + 빈 종료 청크 emit.
	 *    (M6-1 끝 또는 M7 에서 별도 ScanErrorEvent 추가 예정.)
	 * 
	 *  # AppHandle 구체 타입
	 *  `AppHandle<tauri::Wry>` 로 고정 (제너릭 `<R: Runtime>` 은 collect_commands!
	 *  매크로가 타입 추론 실패함 — 2026-04 시점 tauri-specta rc.24 한계).
	 *  Wry 가 우리 builder 의 런타임이므로 손실 없음.
	 */
	startDirectoryScan: (path: string, maxDepth: number) => typedError<null, string>(__TAURI_INVOKE("start_directory_scan", { path, maxDepth })),
};

/** Events */
export const events = {
	nodeChunkEvent: makeEvent<NodeChunkEvent>("node-chunk-event"),
};

/* Types */
/**
 *  3D 공간 노드 (파일, 링크, 메모 등의 개체)
 * 
 *  # 필드
 *  - `id`: 고유 식별자 (UUID 형식 권장, 다음 마일스톤)
 *  - `path`: 로컬 파일시스템 경로 또는 URL (안전성 검증됨)
 *  - `x`, `y`, `z`: 3D 공간 좌표 (무한 캔버스 위치)
 * 
 *  # serde 매크로 설명
 *  `#[derive(Serialize, Deserialize)]`는 구조체를 자동으로 JSON ↔ Rust 객체 변환
 *  프론트엔드 `src/state/store.ts`의 `Node` 타입과 필드 이름/타입이 반드시 일치해야 함
 *  # `#[serde(rename_all = "camelCase")]` 설명
 * 
 *  Rust 필드 이름은 snake_case 관례 (예: `created_at`, `updated_at`),
 *  그러나 TypeScript/JavaScript는 camelCase 관례 (예: `createdAt`, `updatedAt`).
 *  이 attribute를 붙이면 serde가 직렬화 시 자동으로 snake_case → camelCase 변환.
 *  예를 들어 Rust의 `pub created_at: i64` 필드는 JSON에서 `"createdAt": ...` 로 변환됨.
 * 
 *  왜 지금 당장 필요한가? 현재 필드엔 snake_case가 없지만, 다음 마일스톤에서
 *  `created_at`, `updated_at`, `is_dirty` 같은 필드가 추가될 예정.
 *  지금 이 attribute를 추가하면 앞으로 TS 타입이 undefined로 읽히는 버그를 원천 차단.
 * 
 *  규약: 모든 IPC struct (Node, Project, Metadata 등)는 이 attribute를 반드시 부여.
 */
export type Node = {
	id: string,
	path: string,
	x: number,
	y: number,
	z: number,
};

/**
 *  디렉토리 스캐너가 emit 하는 청크 이벤트 페이로드.
 * 
 *  # 흐름
 *  1. Frontend: `invoke('start_directory_scan', {path, maxDepth})`
 *  2. Rust: 즉시 `Ok(())` 반환 + `tokio::spawn`으로 백그라운드 스캔 시작
 *  3. Rust: 1,000개 노드 모일 때마다 `chunk.emit(&app)` 호출
 *  4. Frontend: `events.nodeChunkEvent.listen((c) => ...)` 로 점진 수신
 *  5. 마지막 청크는 `is_last = true` (남은 노드 수와 무관, 빈 배열일 수도 있음)
 * 
 *  # 필드 결정
 *  - `chunk_id: u32` — 0부터 증가하는 순번. Frontend가 순서 검증/재정렬 용도로 사용.
 *    (현재는 단일 task가 직렬 emit 하므로 순서 보장되지만, 멀티 task 분할 가능성 대비.)
 *  - `nodes: Vec<ScannedNode>` — 이 청크의 페이로드. 최대 `CHUNK_SIZE` (기본 1,000).
 *  - `is_last: bool` — 종료 신호. Frontend가 "스캔 완료" UI 표시.
 *  - `total_scanned: u32` — 누적 노드 수 (이 청크 포함). Progress 표시용.
 * 
 *  # tauri_specta::Event derive
 *  이 derive로 자동 생성되는 것:
 *  - Rust측: `NodeChunkEvent::emit(&self, &AppHandle)` 메서드
 *  - 이벤트 이름: 구조체명 → kebab-case (`"node-chunk-event"`)
 *  - bindings.ts: `events.nodeChunkEvent.listen(handler)` wrapper
 * 
 *  # 왜 NodeChunk가 아닌 NodeChunkEvent인가
 *  일반 데이터 타입 (`Node`, `ScannedNode`)과 이벤트 페이로드를 명명으로 구분.
 *  향후 `ScanProgressEvent`, `ScanErrorEvent` 등 추가 시 일관된 패턴.
 */
export type NodeChunkEvent = {
	chunkId: number,
	nodes: ScannedNode[],
	isLast: boolean,
	totalScanned: number,
};

/**
 *  노드 메타데이터 (선택된 노드 상세 정보 패널용)
 * 
 *  # 필드 타입 결정 근거 (Gemini Pro 자문, 2026-04-23)
 *  - `size_bytes: u64` — 파일 크기. JS Number는 53비트 안전 정수까지 (~9PB),
 *    파일 크기로는 충분. BigInt 변환 불필요.
 *  - `created_at`, `modified_at: i64` — Unix epoch milliseconds. i64는 ~300,000년
 *    범위라 안전. ISO 8601 string 대신 number로 보내는 이유: 페이로드 작고,
 *    파싱 빠르고, 정렬도 number 비교로 가능.
 * 
 *  # camelCase 자동 변환
 *  `size_bytes` → `sizeBytes`, `created_at` → `createdAt`, `modified_at` → `modifiedAt`.
 *  위 `#[serde(rename_all = "camelCase")]`가 처리. tauri-specta가 생성하는
 *  TypeScript 타입에도 자동으로 반영됨.
 */
export type NodeDetails = {
	id: string,
	name: string,
	path: string,
	kind: NodeKind,
	sizeBytes: number,
	createdAt: number,
	modifiedAt: number,
};

/**
 *  노드 종류 (파일/디렉터리/링크/메모)
 * 
 *  프론트엔드에서 아이콘/색상 분기에 사용할 분류값.
 *  `#[serde(rename_all = "camelCase")]` enum variant까지 camelCase로 변환되지는
 *  않지만 (variant는 PascalCase 그대로 유지), 일관성과 안전성 차원에서 부여.
 *  JSON 표현 예: `"file"`, `"directory"`, `"link"`, `"memo"`.
 */
export type NodeKind = "file" | "directory" | "link" | "memo";

/**
 *  비동기 디렉토리 스캐너가 만들어내는 1개 노드.
 * 
 *  기존 `Node` (3D 좌표 보유) / `NodeDetails` (메타패널 전용) 와는 분리한다:
 *  - `Node`: 렌더링 좌표 중심. 3D 위치가 핵심 필드.
 *  - `NodeDetails`: 단일 노드 상세 패널. 타임스탬프 등 풍부한 메타.
 *  - `ScannedNode`: 대량 스트리밍 페이로드. **Step 1에선 좌표 없음** —
 *    Step 2(JSON 청크) 또는 Frontend 단계에서 임시 random 좌표를 부여.
 * 
 *  굳이 합치지 않은 이유: 청크 페이로드 크기를 줄이려면 불필요한 필드를
 *  빼야 하고, 향후 `Node`가 view 전용 / `ScannedNode`가 disk 전용으로
 *  책임 분리를 유지하는 편이 명확하다.
 * 
 *  # 필드 결정 근거
 *  - `id: String` — UUID v7 (시간 정렬 가능). 청크 순서 보장 부담 완화.
 *  - `path: String` — 절대 경로. canonicalize 결과를 그대로 직렬화.
 *  - `name: String` — `path` 끝 segment. frontend가 매번 split 하지 않게 미리 분리.
 *  - `kind: NodeKind` — 기존 enum 재사용 (File/Directory/Link/Memo).
 *  - `size_bytes: u64` — `Node`와 동일 근거 (JS Number 53-bit 안전).
 *  - `depth: u32` — root 기준 깊이. root 직계 자식 = 1, 그 손자 = 2.
 *  - `position: [f32; 3]` — (M7-1 Step 1) Fractal Orbital Packing 으로 계산된
 *    3D 우주 좌표. Frontend 가 더 이상 random 폴백을 만들지 않고 그대로 사용.
 *    `f32` 인 이유: GPU 인스턴스 매트릭스가 `Float32Array` 라 어차피 다운캐스트됨.
 *  - `scale: f32` — (D15 Depth-Aware) 깊이별 인스턴스 스케일. `coords::scale_for_depth(depth)`
 *    결과를 그대로 저장. Frontend 가 InstancedMesh 의 instanceMatrix 에 uniform scale
 *    로 합성. 균일 BASE_RADIUS 가 만들던 D3+ 노드 겹침 문제를 해결한다.
 */
export type ScannedNode = {
	id: string,
	path: string,
	name: string,
	kind: NodeKind,
	sizeBytes: number,
	depth: number,
	position: [number, number, number],
	scale: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

